const QUESTION_STATE_STARTING = "starting";
const QUESTION_STATE_ANSWERING = "answering";
const QUESTION_STATE_SHOW_ANSWER = "show_answer";
const QUESTION_STATE_SHOW_EXPLANATION = "show_explanation";

export {
  QUESTION_STATE_STARTING,
  QUESTION_STATE_ANSWERING,
  QUESTION_STATE_SHOW_ANSWER,
  QUESTION_STATE_SHOW_EXPLANATION,
};
